name: Challenge-1

on  : push

jobs:
  ubuntu :
    runs-on : ubuntu-latest
    steps   :
      - run : date
  windows:
    runs-on : windows-latest
    steps   :
      - run : date
  mac-os :
    runs-on : macos-latest
    steps   :
      - run : date
  custom :
    runs-on : ubuntu-latest
    needs   : [ubuntu,windows,mac-os]
    steps   :
      - run : date
